INSERT INTO restaurante (ABERTO,BLOQUEADO,CNPJ,DESCRICAO,DISPONIVEL,EMAIL,ESTRELAS,HORARIOATENDIMENTO,NOMERESTAURANTE,TELEFONE,VALORTAXAENTREGA) VALUES (1,0,"49.613.374/0001-71","all blue",1,"",1,"","Ceu azul","",1);
INSERT INTO restaurante (ABERTO,BLOQUEADO,CNPJ,DESCRICAO,DISPONIVEL,EMAIL,ESTRELAS,HORARIOATENDIMENTO,NOMERESTAURANTE,TELEFONE,VALORTAXAENTREGA) VALUES (1,0,"85.718.385/0001-80","So pra quem pode",1,"",2,"","farofa chique","",2);
INSERT INTO restaurante (ABERTO,BLOQUEADO,CNPJ,DESCRICAO,DISPONIVEL,EMAIL,ESTRELAS,HORARIOATENDIMENTO,NOMERESTAURANTE,TELEFONE,VALORTAXAENTREGA) VALUES (1,0,"77.772.400/0001-40","Lá tem pao",1,"",3,"","Ceu e Pao","",6);
INSERT INTO restaurante (ABERTO,BLOQUEADO,CNPJ,DESCRICAO,DISPONIVEL,EMAIL,ESTRELAS,HORARIOATENDIMENTO,NOMERESTAURANTE,TELEFONE,VALORTAXAENTREGA) VALUES (1,0,"73.826.052/0001-95","frio absoluto",1,"",4,"","zero grau","",12);
INSERT INTO restaurante (ABERTO,BLOQUEADO,CNPJ,DESCRICAO,DISPONIVEL,EMAIL,ESTRELAS,HORARIOATENDIMENTO,NOMERESTAURANTE,TELEFONE,VALORTAXAENTREGA) VALUES (1,0,"88.378.462/0001-98","super chefs",1,"",5,"","Master chef","",20);


INSERT INTO prato (NOME,VALORPRODUTO,cardapio_id) VALUES ("Suco de Uva",1,1);
INSERT INTO prato (NOME,VALORPRODUTO,cardapio_id) VALUES ("Suco de Manga",2,1);
INSERT INTO prato (NOME,VALORPRODUTO,cardapio_id) VALUES ("Suco de Laranja",5,1);
INSERT INTO prato (NOME,VALORPRODUTO,cardapio_id) VALUES ("Suco de Batata",6,1);
INSERT INTO prato (NOME,VALORPRODUTO,cardapio_id) VALUES ("Suco de Beterraba",1,1);

INSERT INTO prato (NOME,VALORPRODUTO,cardapio_id) VALUES ("Pao batata",1,2);
INSERT INTO prato (NOME,VALORPRODUTO,cardapio_id) VALUES ("Pao batata",1233,1);
INSERT INTO prato (NOME,VALORPRODUTO,cardapio_id) VALUES ("Pao de lo",12,2);
INSERT INTO prato (NOME,VALORPRODUTO,cardapio_id) VALUES ("Pao de sal",136,2);
INSERT INTO prato (NOME,VALORPRODUTO,cardapio_id) VALUES ("Pao doce",9,2);
INSERT INTO prato (NOME,VALORPRODUTO,cardapio_id) VALUES ("Pao baguete",90,2);

INSERT INTO cliente(BLOQUEADO,CPF,EMAIL,GERENTE,NOME,PAPEL,SENHA,TELEFONE,ENDERECO) VALUES(0, 00125445639, "marcus", 0, "marcus", "clienteuser", SHA2("123",256),63255299,"RUA 1");
INSERT INTO cliente(BLOQUEADO,CPF,EMAIL,GERENTE,NOME,PAPEL,SENHA,TELEFONE,ENDERECO) VALUES(0, 00125445639, "tiago", 1, "thiago", "gerenteuser", SHA2("123",256),45674894,"RUA 2");